import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { Miniflare, convertV4MiniflareOptions } from 'miniflare';
import worker from '../cloud/worker.mjs';
import { hasSession, sessionCookie } from '../cloud/auth.mjs';
import { importState, loadState, updateState } from '../cloud/store.mjs';
import { applyAction, createState, cycleView, today } from '../lib/domain.mjs';
import { decodeReceipt } from '../lib/receipts.mjs';

const password = 'test-password-only-for-isolated-fixtures';
const png = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aXt0AAAAASUVORK5CYII=';
async function fixture(t, { initialized = true } = {}) {
  const mf = new Miniflare(convertV4MiniflareOptions({ modules: true, script: 'export default { fetch() { return new Response(); } }', compatibilityDate: '2026-10-05', d1Databases: { DB: 'isolated-test' } }));
  t.after(() => mf.dispose());
  const db = await mf.getD1Database('DB');
  const sql = await readFile(new URL('../cloud/migrations/0001_storage.sql', import.meta.url), 'utf8');
  await db.batch(sql.split(';').filter(s => s.trim()).map(s => db.prepare(s)));
  const date = today(), state = createState(date), month = state.initialMonth;
  if (initialized) await importState(db, state, date);
  const env = { DB: db, APP_PASSWORD: password, ASSETS: { fetch: async () => new Response('<html lang="es-MX">Calendario</html>') } };
  const origin = 'https://renta.example';
  const cookie = (await sessionCookie(password, new URL(origin))).split(';')[0];
  const call = (route, { body, anonymous = false, headers = {}, method = body ? 'POST' : 'GET' } = {}) => worker.fetch(new Request(origin + route, { method, headers: { ...(anonymous ? {} : { Cookie: cookie }), ...(body ? { Origin: origin, 'Content-Type': 'application/json' } : {}), ...headers }, ...(body ? { body: JSON.stringify(body) } : {}) }), env);
  const action = (action, revision = 0) => call('/api/action', { body: { revision, action: { month, ...action } } });
  const payday = cycleView(state, month, date).paydays[0];
  return { db, state, date, month, env, call, action, payday, origin };
}
test('cloud login protects records, images and backups with signed secure sessions', async t => {
  const f = await fixture(t);
  assert.equal((await f.call('/', { anonymous: true })).headers.get('Location'), '/login');
  for (const route of ['/api/cycle', '/api/backup', '/comprobantes/image.png']) assert.equal((await f.call(route, { anonymous: true })).status, 401);
  const request = (key, origin = f.origin) => new Request(f.origin + '/login', { method: 'POST', headers: { Origin: origin, 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ password: key }) });
  assert.equal((await worker.fetch(request('wrong'), f.env)).status, 401);
  assert.equal((await worker.fetch(request(password, 'https://evil.example'), f.env)).status, 403);
  const login = await worker.fetch(request(password), f.env);
  assert.equal(login.status, 303);
  assert.match(login.headers.get('Set-Cookie'), /__Host-renta_session=.*HttpOnly.*SameSite=Strict.*Secure/);
  assert.equal((await f.call('/api/cycle')).status, 200);
  assert.equal((await f.action({ type: 'reopen-payday', id: f.payday.id }, 0)).status, 400);
  const expired = await sessionCookie(password, new URL(f.origin), Date.now() - 8 * 86400000);
  assert.equal(await hasSession(new Request(f.origin, { headers: { Cookie: expired.split(';')[0] } }), password), false);
  assert.equal(await hasSession(new Request('https://other.example', { headers: { Cookie: login.headers.get('Set-Cookie').split(';')[0] } }), password), false);
  const logout = await f.call('/logout', { method: 'POST', headers: { Origin: f.origin } });
  assert.match(logout.headers.get('Set-Cookie'), /Max-Age=0/);
});
test('D1 concurrent saves preserve the winning revision and its cycle backups', async t => {
  const f = await fixture(t);
  const results = await Promise.all([f.action({ type: 'close-payday', id: f.payday.id, paid: 10000 }), f.action({ type: 'close-payday', id: f.payday.id, paid: 20000 })]);
  assert.deepEqual(results.map(r => r.status).sort(), [200, 409]);
  const state = await loadState(f.db);
  assert.equal(state.revision, 1);
  const paid = state.cycles[f.month].paydays[f.payday.id].paid;
  assert.ok([10000, 20000].includes(paid));
  const backup = await f.db.prepare('SELECT * FROM cycle_backups WHERE month = ?').bind(f.month).first();
  assert.equal(JSON.parse(backup.json).cycle.totals.saved, paid);
  assert.equal(JSON.parse(backup.previous_json).revision, 0);
  assert.equal(JSON.parse((await f.db.prepare('SELECT previous_json FROM app_state').first()).previous_json).revision, 0);
  assert.equal((await f.action({ type: 'update-payday', id: f.payday.id, income: f.payday.income, available: 0 }, 1)).status, 400);
  assert.equal((await f.action({ type: 'reopen-payday', id: f.payday.id }, 1)).status, 200);
  const reopened = await (await f.call('/api/cycle')).json();
  assert.equal(reopened.cycle.totals.saved, 0);
  assert.equal(reopened.cycle.paydays[0].previousPaid, paid);
  const download = await f.call(`/api/backup?month=${f.month}`);
  assert.match(download.headers.get('Content-Disposition'), /attachment/);
  assert.equal((await download.json()).revision, 2);
});
test('D1 image uploads are atomic with contributions, bounded and survive reopening', async t => {
  const f = await fixture(t);
  assert.equal((await f.action({ type: 'close-payday', id: f.payday.id, paid: 0 })).status, 200);
  const upload = revision => f.call('/api/receipt', { body: { revision, month: f.month, paydayId: f.payday.id, name: 'captura.png', dataUrl: png } });
  const responses = await Promise.all([upload(1), upload(1)]);
  assert.deepEqual(responses.map(r => r.status).sort(), [200, 409]);
  assert.equal((await f.db.prepare('SELECT COUNT(*) AS count FROM receipts').first()).count, 1);
  const state = await loadState(f.db), receipt = state.cycles[f.month].paydays[f.payday.id].receipts[0];
  const url = `/comprobantes/${f.month}/${receipt.id}`;
  assert.equal((await f.call(url, { anonymous: true })).status, 401);
  const image = await f.call(url);
  assert.equal(image.headers.get('Content-Type'), 'image/png');
  assert.deepEqual(Buffer.from(await image.arrayBuffer()), decodeReceipt(png).buffer);
  assert.equal((await f.action({ type: 'reopen-payday', id: f.payday.id }, 2)).status, 200);
  assert.equal((await f.call(url)).status, 200);
  const big = Buffer.alloc(500001); decodeReceipt(png).buffer.copy(big);
  const tooLarge = await f.call('/api/receipt', { body: { revision: 3, month: f.month, paydayId: f.payday.id, name: 'grande.png', dataUrl: 'data:image/png;base64,' + big.toString('base64') } });
  assert.equal(tooLarge.status, 413);
  const invalid = await f.call('/api/receipt', { body: { revision: 3, month: f.month, paydayId: 'missing', name: 'captura.png', dataUrl: png } });
  assert.equal(invalid.status, 400);
  assert.equal((await f.db.prepare('SELECT COUNT(*) AS count FROM receipts').first()).count, 1);
  assert.equal((await loadState(f.db)).revision, 3);
});
test('initial migration requires every receipt and never replaces existing cloud records', async t => {
  const f = await fixture(t, { initialized: false });
  assert.equal((await f.call('/api/cycle')).status, 503);
  const id = '00000000-0000-4000-8000-000000000000.png';
  const receipt = { id, name: 'captura.png', type: 'image/png', bytes: decodeReceipt(png).buffer.length, uploadedAt: new Date().toISOString() };
  applyAction(f.state, { type: 'attach-receipt', month: f.month, id: f.payday.id, receipt }, f.date);
  assert.equal((await f.call('/api/import', { body: { state: f.state } })).status, 400);
  assert.equal(await f.db.prepare('SELECT id FROM app_state').first(), null);
  assert.equal((await f.call('/api/import/receipt', { body: { month: f.month, id, dataUrl: png } })).status, 200);
  assert.equal((await f.call('/api/import', { body: { state: f.state } })).status, 200);
  assert.equal((await f.call('/api/import', { body: { state: createState() } })).status, 409);
  assert.equal((await f.call('/api/import/receipt', { body: { month: f.month, id, dataUrl: png } })).status, 409);
  assert.equal((await loadState(f.db)).cycles[f.month].paydays[f.payday.id].receipts.length, 1);
});
test('a D1 batch failure rolls back records and backups together', async t => {
  const f = await fixture(t);
  const before = await loadState(f.db);
  const badReceipt = { type: 'image/png', buffer: decodeReceipt(png).buffer, dataUrl: null };
  const receipt = { id: '00000000-0000-4000-8000-000000000000.png', name: 'captura.png', type: 'image/png', bytes: badReceipt.buffer.length, uploadedAt: new Date().toISOString() };
  await assert.rejects(updateState(f.db, before, { type: 'attach-receipt', month: f.month, id: f.payday.id, receipt }, 0, f.date, badReceipt));
  assert.equal((await loadState(f.db)).revision, 0);
  assert.equal((await f.db.prepare('SELECT revision FROM cycle_backups WHERE month = ?').bind(f.month).first()).revision, 0);
});
